name: Test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Setup dependencies
        run: npm install
      - name: Lint files
        run: npx eslint src --ext .js,.jsx,.ts,.tsx
      - name: Compile TypeScript
        run: npx tsc
      - name: Run tests
        run: npm test